JobName: ""
WorkspaceName: 'test-cci'
Aec2Name: "engineer-5090"
priority: Normal
WorkerSpec: n12lp.nn.i10.1 # 1卡5090
TrainingFramework: "pytorch"
Image: registry.cn-sh-01.sensecore.cn/ccr-xworld/service_kairos_sensenova:kairos-20260201133229
MountInfo: 0198e120-51c9-7391-b9be-c7e6f4ac5312:/data_tmp # afs-q-engineer
Env: ""
Command: ""