name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_A800_tasks:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: A800_480p_t2v_1gpu
            case_cmd: "bash .github/commons/examples/inference.sh .github/commons/examples/example_t2v_480P.json .github/commons/examples/configs/kairos_4b_config_DMD_A800.py "
          - job_name: A800_720p_ti2v_4gpu
            case_cmd: "bash .github/commons/examples/multi_gpu_inference.sh .github/commons/examples/example_ti2v.json .github/commons/examples/configs/kairos_4b_config_DMD_A800.py 4 "
    name: ${{ matrix.job_name }}
    uses: ./.github/workflows/huoshan-task-template.yml
    with:
      job_name: ${{ matrix.job_name }}
      task_config_template: .github/commons/template/huoshan-mltask-template.yaml
      task_cmd_file: .github/commons/scripts/huoshan_cmd.sh
      task_config_file: .github/commons/${{ matrix.job_name }}-mltask.yaml
      task_name: kairos-ci-${{ matrix.job_name }}-${{ github.sha }}
      pendding_timeout: 7200
      taskid_file: ${{ matrix.job_name }}_taskid.txt
      case_cmd: ${{ matrix.case_cmd }}
      remote_dir: "kairos-ci/${{ github.sha }}/${{ matrix.job_name }}/"
    secrets:
      VOLC_ACCESS_KEY: ${{ secrets.VOLC_ACCESS_KEY }}
      VOLC_SECRET_KEY: ${{ secrets.VOLC_SECRET_KEY }}
      REGION: ${{ secrets.REGION }}
      HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
      HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
      AOSS_AK:  ${{ secrets.AOSS_AK }}
      AOSS_SK:  ${{ secrets.AOSS_SK }}
  
  run_5090_tasks:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: 5090_480p_ti2v_1gpu
            case_cmd: "bash .github/commons/examples/inference.sh .github/commons/examples/example_ti2v_480P.json .github/commons/examples/configs/kairos_4b_config_DMD_5090.py "
          - job_name: 5090_720p_t2v_4gpu
            case_cmd: "bash .github/commons/examples/multi_gpu_inference.sh  .github/commons/examples/example_t2v.json .github/commons/examples/configs/kairos_4b_config_DMD_5090.py 4"
    name: ${{ matrix.job_name }}
    uses: ./.github/workflows/sensecore-task-template.yml
    with:
      job_name: ${{ matrix.job_name }}
      task_config_template: .github/commons/template/sensecore-acp-template.yaml
      task_cmd_file: .github/commons/scripts/sensecore_cmd.sh
      task_config_file: .github/commons/${{ matrix.job_name }}-task.yaml
      task_name: kairos-ci-${{ matrix.job_name }}-${{ github.sha }}
      pendding_timeout: 7200
      taskid_file: ${{ matrix.job_name }}_taskid.txt
      case_cmd: ${{ matrix.case_cmd }}
      remote_dir: "kairos-ci/${{ github.sha }}/${{ matrix.job_name }}/"
    secrets:
      AOSS_AK:  ${{ secrets.AOSS_AK }}
      AOSS_SK:  ${{ secrets.AOSS_SK }}
      ZONE:  ${{ secrets.ZONE }}
      HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
      HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}